#!/bin/bash

STRING="Install Components for Mac OSx"

#
#lets start in the home dir
#
cd ~

#print variable on a screen
echo $STRING

SITES_DIR="~/Sites"

if [ -d "$SITES_DIR" ]
then
	echo "$SITES_DIR directory  exists!"
else
	echo "$SITES_DIR directory not found!"
	mkdir ~/Sites
fi

chflags nohidden ~/Library/

#
#install homebrew -> https://github.com/mxcl/homebrew/wiki/installation
#
/usr/bin/ruby -e "$(/usr/bin/curl -fksSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"

sudo chown $USER /usr/local

brew update

brew install git bash-completion byobu ssh-copy-id wget

echo "install tomcat 6"
cd /usr/local/Library/Formula
git checkout 9e18876 tomcat.rb
brew install tomcat
cd -
echo "installation of tomcat 6 completed"



